name: pettix
description: "Pet Care App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1

  # Google Sign-In
  google_sign_in: ^6.2.2
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  flex_color_scheme: ^8.2.0
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.0.0+2

  # State Management & Architecture
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Networking
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  intl: 0.19.0

  # Caching & Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Logging & Debugging
  talker: ^4.8.0
  talker_flutter: ^4.8.0
  talker_dio_logger: ^4.8.0
  talker_bloc_logger: ^4.8.0

  # Routing & Navigation
  go_router: ^15.1.2

  # Localization & Translations
  easy_localization: ^3.0.7+1

  # Configuration & Environment
  envied: ^1.1.1

  # Permissions & Connectivity
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_flavorizr: ^2.4.1



flavorizr:
  app:
    android:
      flavorDimensions: "app"
  flavors:
    dev:
      app:
        name: "MyApp Dev"
      android:
        applicationId: "com.example.myapp.dev"
    prod:
      app:
        name: "MyApp"
      android:
        applicationId: "com.example.myapp"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
